// src/components/Footer.js
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faFacebook, faInstagram, faYoutube, faTwitter, faLinkedin, faMedium, faTiktok } from '@fortawesome/free-brands-svg-icons';

import Popup from 'reactjs-popup';
import 'reactjs-popup/dist/index.css';

import { IoMdClose } from "react-icons/io";

import './index.css';
const Footer = () => {
  return (
    <footer className="footer">
      <div className="footer-social">
        <a href='https://www.facebook.com/profile.php?id=100007295141097' target='_blank' className='icons-link'><FontAwesomeIcon icon={faFacebook} /></a>
        <a href='https://www.instagram.com/srikanth_4441/' target='_blank' className='icons-link'><FontAwesomeIcon icon={faInstagram} /></a>
        <a href='https://www.youtube.com/@TechnicalSrikanth' target='_blank' className='icons-link'><FontAwesomeIcon icon={faYoutube} /></a>
        <a href='' target='_blank' className='icons-link'><FontAwesomeIcon icon={faTwitter} /></a>
        <a href='https://www.linkedin.com/in/kongala-srikanth/' target='_blank' className='icons-link'><FontAwesomeIcon icon={faLinkedin} /></a>
        <a href='' target='_blank' className='icons-link'><FontAwesomeIcon icon={faMedium} /></a>
        <a href='' target='_blank' className='icons-link'><FontAwesomeIcon icon={faTiktok} /></a>
      </div>
      
      <div className="footer-links">
        <a href="#home">Home</a>
        <a href="#about">About</a>
        <a href="#skills">Skills</a>
        <a href="#projects">Projects</a>
        <a href="#certificates">Certificates</a>
        <Popup modal trigger={<a>Privacy Policy</a>} position="center">{
          close => (<div className='privacy-popup-container'>
            <div className='privacy-close-btn-contaier'>
              <button type='button' className='privacy-close-btn' onClick={close}>
                <IoMdClose className='privacy-close-icon' />
              </button>
            </div>
            
            <h1>Privacy Policy for Portfolio</h1>
  
            <p><strong>Last updated:</strong> August 11, 2024</p>
  
            <p>This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
  
            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Free Privacy Policy Generator.</p>
  
            <h2 className='h2-sub-heading'>Interpretation and Definitions</h2>
  
            <h3>Interpretation</h3>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
  
            <h3>Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
  
            <ul>
                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Portfolio.</li>
                <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                <li><strong>Country</strong> refers to: Telangana, India</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the Website.</li>
                <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>Website</strong> refers to Portfolio.</li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
  
            <h2 className='h2-sub-heading'>Collecting and Using Your Personal Data</h2>
  
            <h3>Types of Data Collected</h3>
  
            <h4>Personal Data</h4>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
  
            <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Usage Data</li>
            </ul>
  
            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p>
  
            <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
  
            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
  
            <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
  
            <h3>Tracking Technologies and Cookies</h3>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
  
            <ul>
                <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
            </ul>
  
            <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
  
            <h4>We use both Session and Persistent Cookies for the purposes set out below:</h4>
  
            <ul>
                <li><strong>Necessary / Essential Cookies</strong>
                    <ul>
                        <li><strong>Type:</strong> Session Cookies</li>
                        <li><strong>Administered by:</strong> Us</li>
                        <li><strong>Purpose:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</li>
                    </ul>
                </li>
                <li><strong>Cookies Policy / Notice Acceptance Cookies</strong>
                    <ul>
                        <li><strong>Type:</strong> Persistent Cookies</li>
                        <li><strong>Administered by:</strong> Us</li>
                        <li><strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on the Website.</li>
                    </ul>
                </li>
                <li><strong>Functionality Cookies</strong>
                    <ul>
                        <li><strong>Type:</strong> Persistent Cookies</li>
                        <li><strong>Administered by:</strong> Us</li>
                        <li><strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
                    </ul>
                </li>
            </ul>
  
            <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
  
            <h2 className='h2-sub-heading'>Use of Your Personal Data</h2>
                <p>The Company may use Personal Data for the following purposes:</p>
                <ul>
                    <li><strong>To provide and maintain our Service,</strong> including monitoring its usage.</li>
                    <li><strong>To manage Your Account</strong> as a registered user of the Service.</li>
                    <li><strong>For the performance of a contract</strong> for products or services You have purchased.</li>
                    <li><strong>To contact You</strong> via email, calls, SMS, or other forms of communication about updates, services, and security.</li>
                    <li><strong>To provide You with news, special offers,</strong> and information about similar goods, services, and events.</li>
                    <li><strong>To manage Your requests</strong> to Us.</li>
                    <li><strong>For business transfers,</strong> such as mergers or sales of Company assets.</li>
                    <li><strong>For other purposes,</strong> like data analysis and improving our Service.</li>
                </ul>
  
                <h2 className='h2-sub-heading'>We may share Your personal information in the following situations:</h2>
                <ul>
                    <li><strong>With Service Providers</strong> to monitor and analyze our Service usage and to contact You.</li>
                    <li><strong>For business transfers,</strong> such as mergers or sales of Company assets.</li>
                    <li><strong>With Affiliates</strong> under our control who will honor this Privacy Policy.</li>
                    <li><strong>With business partners</strong> to offer You products, services, or promotions.</li>
                    <li><strong>With other users</strong> in public areas of the Service.</li>
                    <li><strong>With Your consent</strong> for any other purpose.</li>
                </ul>
  
                <h2 className='h2-sub-heading'>Retention of Your Personal Data</h2>
                <p>The Company will retain Your Personal Data only as long as necessary to fulfill the purposes outlined in this Privacy Policy. We may also retain and use Your Personal Data to comply with legal obligations, resolve disputes, and enforce legal agreements.</p>
  
                <h2 className='h2-sub-heading'>Transfer of Your Personal Data</h2>
                <p>Your information may be transferred to—and maintained on—computers outside of Your state, province, country, or other governmental jurisdiction. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
  
                <h2 className='h2-sub-heading'>Delete Your Personal Data</h2>
                <p>You have the right to delete or request assistance in deleting Personal Data collected about You. You can update, amend, or delete Your information by signing in to Your Account or contacting Us.</p>
  
                <h2 className='h2-sub-heading'>Disclosure of Your Personal Data</h2>
                <p>The Company may disclose Your Personal Data in connection with business transactions, to comply with legal obligations, protect the Company's rights, prevent wrongdoing, protect public safety, or protect against legal liability.</p>
  
                <h2 className='h2-sub-heading'>Security of Your Personal Data</h2>
                <p>While We strive to protect Your Personal Data, no method of transmission or electronic storage is 100% secure. We cannot guarantee its absolute security.</p>
  
                <h2 className='h2-sub-heading'>Children's Privacy</h2>
                <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personal information from anyone under 13 without parental consent. If We discover such information has been collected, We will take steps to remove it from Our servers.</p>
  
                <h2 className='h2-sub-heading'>Links to Other Websites</h2>
                <p>Our Service may contain links to other websites not operated by Us. We are not responsible for the content, privacy policies, or practices of any third-party sites or services.</p>
  
                <h2 className='h2-sub-heading'>Changes to this Privacy Policy</h2>
                <p>We may update this Privacy Policy from time to time. Changes will be posted on this page, and You are advised to review it periodically.</p>
  
                <h2 className='h2-sub-heading'>Contact Us</h2>
                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul>
                    <li>By email: <a href="mailto:kongala.srikanth44@gmail.com">kongala.srikanth44@gmail.com</a></li>
                    
                </ul>
  
                <p>Generated using Free Privacy Policy Generator</p>
              </div>)
        }
          
        </Popup>
        
      </div>
      
      <div className="footer-logo">
        <p>© 2024 Srikanth Kongala</p>
      </div>
    </footer>
  );
}

export default Footer;


// <li>By visiting this page on our website: <a href="https://kongalasrikanth.info/contact">https://kongalasrikanth.info/contact</a></li>